# --- represents this file as a playbook
---
# Use [space]play[space] where play is combination of hosts+tasks

- hosts: all
  gather_facts: yes
  # Become root user
  become: yes
  any_errors_fatal: true
  # List of tasks to be executed
  roles:
    - packages
    - i3
    - fonts
    - settings
    - role: private
      tags:
        - never
        - private
  post_tasks:
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
