---
# tasks file for i3

- name: Add i3-gaps PPA
  apt_repository:
    repo: ppa:kgilmer/speed-ricer

- name: Install Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - i3-gaps
      - nitrogen
      - rofi
      - feh
      - sakura

- name: Ensures directories exist
  file:
    path: "~/.config/i3"
    state: directory
  become: no

- name: Copy config files
  copy:
    src: "{{ item }}"
    dest: "~/.config/i3/{{ item | basename }}"
    mode: "+x"
  with_fileglob:
    - ../files/i3/*
  become: no

- name: Copy .Xresources
  copy:
    src: ".Xresources"
    dest: "~/.Xresources"
  become: no

- name: Ensures Sakura conf directories exist
  file:
    path: "~/.config/sakura"
    state: directory
  become: no

- name: Copy Sakura Conf
  copy:
    src: "sakura.conf"
    dest: "~/.config/sakura/sakura.conf"
  become: no

- name: Ensures Rofi themes directories exist
  file:
    path: "~/.local/share/rofi/themes"
    state: directory
  become: no

- name: Copy onedark theme
  copy:
    src: "onedark.rasi"
    dest: "~/.local/share/rofi/themes"
  become: no
