---
# tasks file for settings

- name: Enable Automatic Login
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: '^#  AutomaticLoginEnable = true'
    line: 'AutomaticLoginEnable = true'

- name: Change the user to dhyan
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: '^#  AutomaticLogin = user1'
    line: 'AutomaticLogin = dhyan'

- name: Add User to Virtual Box Group
  command: "usermod -a -G vboxsf dhyan"

- name: Setup Git user
  command: "{{ item }}"
  with_items:
    - "git config --global user.name 'Dhyan Raj'"
    - "git config --global user.email 'dhyan.raj@synechron.com'"
